export const SHOP_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device'
export const PAYMENT_ROUTE = '/payment'
export const STATUS_ROUTE = '/status'